module.exports = {
  schemas: {
    ["api.github.com.deref"]: require("./generated/api.github.com.deref.json"),
    ["api.github.com"]: require("./generated/api.github.com.json"),
    ["ghec.deref"]: require("./generated/ghec.deref.json"),
    ["ghec"]: require("./generated/ghec.json"),
    ["ghes-3.14.deref"]: require("./generated/ghes-3.14.deref.json"),
    ["ghes-3.14"]: require("./generated/ghes-3.14.json"),
    ["ghes-3.15.deref"]: require("./generated/ghes-3.15.deref.json"),
    ["ghes-3.15"]: require("./generated/ghes-3.15.json"),
    ["ghes-3.16.deref"]: require("./generated/ghes-3.16.deref.json"),
    ["ghes-3.16"]: require("./generated/ghes-3.16.json"),
    ["ghes-3.17.deref"]: require("./generated/ghes-3.17.deref.json"),
    ["ghes-3.17"]: require("./generated/ghes-3.17.json"),
    ["ghes-3.18.deref"]: require("./generated/ghes-3.18.deref.json"),
    ["ghes-3.18"]: require("./generated/ghes-3.18.json"),
    ["ghes-3.19.deref"]: require("./generated/ghes-3.19.deref.json"),
    ["ghes-3.19"]: require("./generated/ghes-3.19.json"),
  },
};
