module.exports = {
  schemas: {
    ["api.github.com.deref"]: require("./generated/api.github.com.deref.json"),
    ["api.github.com"]: require("./generated/api.github.com.json"),
    ["ghec.deref"]: require("./generated/ghec.deref.json"),
    ["ghec"]: require("./generated/ghec.json"),
    ["ghes-3.10.deref"]: require("./generated/ghes-3.10.deref.json"),
    ["ghes-3.10"]: require("./generated/ghes-3.10.json"),
    ["ghes-3.11.deref"]: require("./generated/ghes-3.11.deref.json"),
    ["ghes-3.11"]: require("./generated/ghes-3.11.json"),
    ["ghes-3.12.deref"]: require("./generated/ghes-3.12.deref.json"),
    ["ghes-3.12"]: require("./generated/ghes-3.12.json"),
    ["ghes-3.13.deref"]: require("./generated/ghes-3.13.deref.json"),
    ["ghes-3.13"]: require("./generated/ghes-3.13.json"),
    ["ghes-3.14.deref"]: require("./generated/ghes-3.14.deref.json"),
    ["ghes-3.14"]: require("./generated/ghes-3.14.json"),
    ["ghes-3.15.deref"]: require("./generated/ghes-3.15.deref.json"),
    ["ghes-3.15"]: require("./generated/ghes-3.15.json"),
    ["github.ae.deref"]: require("./generated/github.ae.deref.json"),
    ["github.ae"]: require("./generated/github.ae.json"),
  },
};
